# Generated by Django 3.2.23 on 2023-11-07 16:39

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrintedReportsHistory',
            fields=[
                ('seq', models.CharField(db_column='Sequence', max_length=6, primary_key=True, serialize=False)),
                ('fosa', models.CharField(db_column='Fosa', max_length=248)),
                ('start_date', core.fields.DateField(blank=True, db_column='startDate', null=True)),
                ('end_date', core.fields.DateField(blank=True, db_column='endDate', null=True)),
            ],
            options={
                'db_table': 'tblPrintedReportsHistory',
            },
        ),
    ]
